export const cardsData = [
  {
    id: 1,
    title: "Task 1",
    datetime: "2020-01-01",
    creator: "John Doe",
    description: "This is a task 1",
    type: "todo",
    priority: "low",
  },
  {
    id: 2,
    title: "Task 2",
    datetime: "2020-01-01",
    creator: "John Doe",
    description: "This is a task 1",
    type: "todo",
    priority: "low",
  },
  {
    id: 3,
    title: "Task 3",
    datetime: "2020-01-01",
    creator: "John Doe",
    description: "This is a task 1",
    type: "todo",
    priority: "low",
  },
  {
    id: 4,
    title: "Task 4",
    datetime: "2020-01-01",
    creator: "John Doe",
    description: "This is a task 1",
    type: "todo",
    priority: "low",
  },
  {
    id: 5,
    title: "Task 5",
    datetime: "2020-01-01",
    creator: "John Doe",
    description: "This is a task 1",
    type: "todo",
    priority: "low",
  },
  {
    id: 6,
    title: "Task 6",
    datetime: "2020-01-01",
    creator: "John Doe",
    description: "This is a task 1",
    type: "todo",
    priority: "low",
  },
];
